source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

xcodeproj '/Users/konstantinefimenko/Documents/Projects/CreativeWebmedia/CreativeWebmedia.xcodeproj'

pod 'Alamofire', '~> 3.0'
pod 'AlamofireImage', '~> 2.0'
pod 'OHHTTPStubs'
pod 'OHHTTPStubs/Swift'
